### ISSUE TITLE
Batch jobs

### ISSUE THREAD

**Issue by anhtuank7c** [seanliang/ConvertToUTF8#61] opened 2016-01-06 02:14 UTC
Dear seanliang.
I have over thousand files need tobe convert to euc-jp.
How to do that?
Does this plugin support convert multible?

**Comment by seanliang** [comment] 2016-01-18 08:31
Sorry, but this feature is not supported (yet).

**Comment by tranngadhkh** [comment] 2016-01-20 15:35
Thanks, supported :)

**Comment by seanliang** [comment] 2016-02-22 07:49
duplicate of #56

**Closed by seanliang** 2016-02-22 07:49 UTC
