### ISSUE TITLE
已安装Codecs33 依然提示找不到codec让安装Codecs33

### ISSUE THREAD

**Issue by beyond2002** [seanliang/ConvertToUTF8#94] opened 2019-01-27 05:45 UTC
startup, version: 3188 linux x64 channel: dev
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/liud/.config/sublime-text-3/Packages
state path: /home/liud/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/liud/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.129102
startup time: 0.246464
first paint time: 0.284897
scan: /home/liud/Downloads/econet/tclinux_phoenix/linux-3.18.21/arch/arm/boot/dts/include/dt-bindings has been seen before, skipping (using inode) previous path: /home/liud/Downloads/econet/tclinux_phoenix/linux-3.18.21/include/dt-bindings inode: 8795914
scan: /home/liud/Downloads/econet/tclinux_phoenix/linux-3.18.21/arch/metag/boot/dts/include/dt-bindings has been seen before, skipping (using inode) previous path: /home/liud/Downloads/econet/tclinux_phoenix/linux-3.18.21/include/dt-bindings inode: 8795914
scan: /home/liud/Downloads/econet/tclinux_phoenix/linux-3.18.21/arch/mips/boot/dts/include/dt-bindings has been seen before, skipping (using inode) previous path: /home/liud/Downloads/econet/tclinux_phoenix/linux-3.18.21/include/dt-bindings inode: 8795914
scan: /home/liud/Downloads/econet/tclinux_phoenix/linux-3.18.21/arch/powerpc/boot/dts/include/dt-bindings has been seen before, skipping (using inode) previous path: /home/liud/Downloads/econet/tclinux_phoenix/linux-3.18.21/include/dt-bindings inode: 8795914
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Codecs33.Codecs33
reloading plugin ConvertToUTF8.ConvertToUTF8
plugins loaded
Detected UTF-8 vs UTF-8 with 99% confidence
Detected GB2312 vs Western (Windows 1252) with 99% confidence
Detected GB2312 vs Western (Windows 1252) with 99% confidence
Package Control: Skipping automatic upgrade, last run at 2019-01-27 12:49:30, next run at 2019-01-27 13:49:30 or after

**Comment by beyond2002** [comment] 2019-01-27 05:50
>>> sublime.version(), sublime.platform(), sublime.arch(), sublime.sys.path
('3188', 'linux', 'x64', ['/opt/sublime_text', '/opt/sublime_text/python3.3.zip', '/home/liud/.config/sublime-text-3/Lib/python3.3', '/home/liud/.config/sublime-text-3/Packages', '/home/liud/.config/sublime-text-3/Packages/Codecs33/lib'])

**Comment by seanliang** [comment] 2019-02-14 02:05
Duplicate of #93 
This problem will be fixed in next build, please downgrade the version to 3176 for now.
该问题将在下个版本修复，目前需要使用请降级到3176及以下版本。

**Closed by seanliang** 2019-02-14 02:05 UTC
